alectra:
  userID: "alectra@alectra.ca"
  password: "aclectrapassword"
  urlAlectra: "https://myaccount.alectrautilities.com"
  influxAddress: "https://influx.host:8086"
  influxPass: "influx_api_key=="
  rootCAs: |
    -----BEGIN CERTIFICATE-----
    CERTIFICATE==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    CERTIFICATE==
    -----END CERTIFICATE-----